### ISSUE TITLE
any reason this returns a function instead of just the regex?

### ISSUE THREAD

**Issue by mafintosh** [chalk/ansi-regex#9]
just curious :)

**Comment by sindresorhus** [comment]
It's a function so you can create multiple instances. Regexes with the global flag will have the .lastIndex property changed for each call to methods on the instance. Therefore reusing the instance with multiple calls will not work as expected for `RegExp#test()`.

**Comment by Qix-** [comment]
@sindresorhus I'm not sure about this looking at MDN again. [`RegExp#exec()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec) states they both increment `lastIndex`, but I believe that gets reset if the input string is different.

If anything, we could do a `get() {}` on it instead of return a function. I agree that returning a function is a strange and messy API.

**Comment by sindresorhus** [comment]
```js
const re = /\w+/g;

console.log(re.test('foo'));
//=> true
console.log(re.test('foo'));
//=> false
```

**Comment by sindresorhus** [comment]
> I agree that returning a function is a strange and messy API.

I disagree. It's RegExp that is strange and messy. We could really use ImmutableRegExp. Actually, we could use immutable for most types.

**Comment by Qix-** [comment]
I tested this earlier and got something completely different I thought, which troubles me a bit. Going to have to test that again next time I'm on that particular box to see what's up.
